version: "3.8"

services:

  db_projeto04:
    container_name: database_projeto04
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=projeto04_database
    volumes:
      - pgdata:/data/postgresql

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  app:
    build: .
    container_name: projeto04
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - db_projeto04
      - redis
    depends_on:
      - db_projeto04
      - redis

volumes:
  pgdata:
    driver: local
